from typing import Callable, Dict
from lm import run_local_lm


class Dialectics:
    """
    Dialectic Reasoning.
    Manages dialectic debates (Thesis, Antithesis, Synthesis)
    conducted by Tiferet.
    """

    def __init__(self, get_settings_fn: Callable[[], Dict], log_fn: Callable[[str], None] = print):
        self.get_settings = get_settings_fn
        self.log = log_fn

    def run_debate(self, topic: str, context: str = "") -> str:
        """
        Run a dialectic debate.
        1. Thesis (Expansion)
        2. Antithesis (Constraint)
        3. Synthesis (Balance)
        All generated by Tiferet.
        """
        settings = self.get_settings()

        self.log(f"🏛️ Tiferet initiating Dialectic Analysis on: {topic}")

        # 1. Thesis
        thesis_prompt = (
            f"TOPIC: {topic}\n"
            f"CONTEXT: {context}\n"
            "ROLE: You are TIFERET (The Decider). You are generating a THESIS.\n"
            "TASK: Propose a strong, affirmative argument or plan regarding this topic. Be bold and constructive.\n"
            "Output ONLY the Thesis."
        )
        thesis_voice = run_local_lm(
            [{"role": "user", "content": thesis_prompt}],
            temperature=0.8,
            max_tokens=300,
            base_url=settings.get("base_url"),
            chat_model=settings.get("chat_model")
        )
        self.log(f"🌱 Thesis: {thesis_voice}")

        # 2. Antithesis
        antithesis_prompt = (
            f"TOPIC: {topic}\n"
            f"THESIS: {thesis_voice}\n"
            "ROLE: You are TIFERET (The Decider). You are generating an ANTITHESIS.\n"
            "TASK: Critique the Thesis. Identify flaws, risks, counter-arguments, or constraints.\n"
            "Output ONLY the Antithesis."
        )
        antithesis_voice = run_local_lm(
            [{"role": "user", "content": antithesis_prompt}],
            temperature=0.8,
            max_tokens=300,
            base_url=settings.get("base_url"),
            chat_model=settings.get("chat_model")
        )
        self.log(f"⚔️ Antithesis: {antithesis_voice}")

        # 3. Tiferet (Synthesis)
        synthesis_prompt = (
            f"TOPIC: {topic}\n"
            f"THESIS: {thesis_voice}\n"
            f"ANTITHESIS: {antithesis_voice}\n"
            "ROLE: You are TIFERET (The Decider). You are generating the SYNTHESIS.\n"
            "TASK: Synthesize a final conclusion that resolves the conflict between Thesis and Antithesis. Find the higher truth.\n"
            "Output ONLY the Synthesis."
        )
        synthesis = run_local_lm(
            [{"role": "user", "content": synthesis_prompt}],
            temperature=0.6,
            max_tokens=500,
            base_url=settings.get("base_url"),
            chat_model=settings.get("chat_model")
        )

        self.log(f"👑 Tiferet Synthesis: {synthesis}")
        return synthesis