import logging
from typing import Callable, Dict, Optional, Any
from ai_core.lm import run_local_lm, compute_embedding


class Dialectics:
    """
    Dialectic Reasoning.
    Manages dialectic debates (Thesis, Antithesis, Synthesis)
    conducted by Tiferet.
    """
    def __init__(self, get_settings_fn: Callable[[], Dict], log_fn: Callable[[str], None] = logging.info, memory_store=None, hesed=None, gevurah=None, event_bus=None):
        self.get_settings = get_settings_fn
        self.log = log_fn
        self.memory_store = memory_store
        self.hesed = hesed
        self.gevurah = gevurah
        self.event_bus = event_bus

    def run_debate(self, topic: str, context: str = "", reasoning_store=None) -> str:
        """
        Run a dialectic debate.
        1. Thesis (Expansion)
        2. Antithesis (Constraint)
        3. Synthesis (Balance)
        All generated by Tiferet.
        """
        settings = self.get_settings()

        # Get dynamic system state
        hesed_val = self.hesed.calculate() if self.hesed else 1.0
        gevurah_val = self.gevurah.calculate() if self.gevurah else 0.0

        self.log(f"🏛️ Tiferet initiating Dialectic Analysis on: {topic} (H:{hesed_val:.2f}, G:{gevurah_val:.2f})")

        # 1. Thesis
        # Dynamic Hesed: High budget = Wild/Creative; Low budget = Cautious
        thesis_temp = 0.7 + (hesed_val * 0.2) # Range 0.7 - 0.9
        thesis_instruction = "Propose a strong, affirmative argument or plan regarding this topic. Focus on potential, growth, optimism, and possibility."
        
        if hesed_val > 0.8:
            thesis_instruction += " Be wild, creative, and unconstrained. Ignore limits."
            thesis_temp = 0.9
        elif hesed_val < 0.4:
            thesis_instruction = "Propose a cautious but affirmative argument. Focus on safe growth and incremental steps."
            thesis_temp = 0.5

        thesis_prompt = (
            f"TOPIC: {topic}\n"
            f"CONTEXT: {context}\n"
            "ROLE: You are HESED (The Force of Expansion).\n"
            f"TASK: {thesis_instruction}\n"
            "Output ONLY the Thesis."
        )
        
        # Retry logic for Thesis
        thesis_voice = ""
        for _ in range(3):
            thesis_voice = run_local_lm(
                [{"role": "user", "content": thesis_prompt}],
                temperature=thesis_temp,
                max_tokens=300,
                base_url=settings.get("base_url"),
                chat_model=settings.get("chat_model")
            )
            if thesis_voice and len(thesis_voice) > 20:
                break
        
        if not thesis_voice or len(thesis_voice) <= 20:
            self.log("❌ Dialectics: Failed to generate Thesis. Aborting debate.")
            return "Debate aborted due to generation failure."
            
        self.log(f"🌱 Thesis: {thesis_voice}")

        # Search for past failures/struggles (The Shadow) in Reasoning Store
        past_failures = ""
        if reasoning_store:
            similar_struggles = reasoning_store.search(topic, top_k=2)
            if similar_struggles:
                past_failures = "\n".join([f"- {s['content']}" for s in similar_struggles])
        
        # Enhancement: Search for REFUTED_BELIEFS in Memory Store (The Deep Shadow)
        if self.memory_store:
            # We search for refuted beliefs related to the topic
            # Assuming we can compute embedding or just search text if embedding not avail here easily
            # For simplicity, we'll use text search if embedding fn isn't handy, or rely on memory_store.search if it handles text
            # memory_store.search expects embedding. Let's try to get refuted memories via SQL text match for robustness
            with self.memory_store._connect() as con:
                rows = con.execute("SELECT text FROM memories WHERE type='REFUTED_BELIEF' AND text LIKE ? LIMIT 3", (f"%{topic}%",)).fetchall()
                if rows:
                    refuted_text = "\n".join([f"- {r[0]}" for r in rows])
                    if past_failures: past_failures += "\n"
                    past_failures += f"REFUTED BELIEFS:\n{refuted_text}"

        shadow_context = ""
        if past_failures:
            shadow_context = f"PAST INTERNAL STRUGGLES (THE SHADOW):\n{past_failures}\n"

        # 2. Antithesis
        # Dynamic Gevurah: High pressure = Ruthless/Precise; Low pressure = Constructive
        antithesis_temp = 0.5
        antithesis_instruction = "Critique the Thesis. Identify flaws, risks, counter-arguments, boundaries, and necessary limits."

        if gevurah_val > 0.7:
            antithesis_temp = 0.1
            antithesis_instruction = "You are RUTHLESS. Destroy the Thesis. Find every flaw, risk, and contradiction. Be brief, harsh, and precise."
        elif gevurah_val < 0.2:
            antithesis_temp = 0.6
            antithesis_instruction = "Provide a constructive critique. Point out minor risks but remain open-minded."

        antithesis_prompt = (
            f"TOPIC: {topic}\n"
            f"THESIS (HESED): {thesis_voice}\n"
            f"{shadow_context}"
            "ROLE: You are GEVURAH (The Force of Constraint).\n"
            f"TASK: {antithesis_instruction}\n"
            "Use the past failures to shred the current Thesis if applicable.\n"
            "Output ONLY the Antithesis."
        )
        antithesis_voice = run_local_lm(
            [{"role": "user", "content": antithesis_prompt}],
            temperature=antithesis_temp,
            max_tokens=300,
            base_url=settings.get("base_url"),
            chat_model=settings.get("chat_model")
        )
        self.log(f"⚔️ Antithesis: {antithesis_voice}")

        # Store the struggle before the conclusion
        if reasoning_store:
            reasoning_store.add(
                content=f"Internal Debate on {topic}: Hesed ({thesis_voice[:50]}...) vs Gevurah ({antithesis_voice[:50]}...)",
                source="dialectics_friction",
                confidence=0.7,
                ttl_seconds=43200, # 12 hours - transient struggle
                metadata={"topic": topic, "stage": "conflict"}
            )

        # 3. Tiferet (Synthesis)
        synthesis_prompt = (
            f"TOPIC: {topic}\n"
            f"THESIS (HESED): {thesis_voice}\n"
            f"ANTITHESIS (GEVURAH): {antithesis_voice}\n"
            "ROLE: You are TIFERET (The Decider/Balance). You are generating the SYNTHESIS.\n"
            "TASK: Synthesize a final conclusion that resolves the conflict between Thesis and Antithesis. Find the higher truth.\n"
            "Output ONLY the Synthesis."
        )
        synthesis = run_local_lm(
            [{"role": "user", "content": synthesis_prompt}],
            temperature=0.6,
            max_tokens=500,
            base_url=settings.get("base_url"),
            chat_model=settings.get("chat_model")
        )

        self.log(f"👑 Tiferet Synthesis: {synthesis}")

        if reasoning_store:
            reasoning_store.add(
                content=f"Synthesis for {topic}: {synthesis}",
                source="tiferet_synthesis",
                confidence=0.9,
                ttl_seconds=86400 * 3, # 3 days - keep the wisdom longer
                metadata={"topic": topic, "stage": "resolution"}
            )

        # Enhancement: Promote Synthesis to Long-Term Memory (Da'at/Binah)
        if self.memory_store and len(synthesis) > 20:
            identity = self.memory_store.compute_identity(synthesis, "BELIEF")
            self.memory_store.add_entry(
                identity=identity,
                text=f"Dialectic Synthesis on {topic}: {synthesis}",
                mem_type="BELIEF",
                subject="Assistant",
                confidence=0.95,
                source="dialectics_synthesis"
            )

        return synthesis